<?php

declare(strict_types=1);

namespace App\Services;

/**
 * Serviço de criptografia simétrica para dados sensíveis.
 * Symmetric encryption service for sensitive data.
 */
class Encryption
{
    /**
     * Criptografa um valor usando AES-256-CBC.
     * Encrypts a value using AES-256-CBC.
     *
     * @param string $value Valor em texto plano.
     * @param string $key Chave de aplicação.
     * @return string Payload em base64 (IV + ciphertext).
     */
    public static function encrypt(string $value, string $key): string
    {
        $iv = random_bytes(16);
        $cipher = openssl_encrypt($value, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);

        return base64_encode($iv . $cipher);
    }

    /**
     * Descriptografa payload base64 gerado por encrypt().
     * Decrypts a base64 payload generated by encrypt().
     *
     * @param string $payload Payload (IV + ciphertext em base64).
     * @param string $key Chave de aplicação.
     * @return string Valor em texto plano ou string vazia em caso de falha.
     */
    public static function decrypt(string $payload, string $key): string
    {
        $decoded = base64_decode($payload, true);
        if ($decoded === false) {
            return '';
        }

        $iv = substr($decoded, 0, 16);
        $ciphertext = substr($decoded, 16);

        return openssl_decrypt($ciphertext, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv) ?: '';
    }
}
